# Generated by Django 3.1.3 on 2021-01-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_model',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
