# Generated by Django 3.1.3 on 2021-01-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210125_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_model',
            old_name='completed_time',
            new_name='Completed_time',
        ),
        migrations.RenameField(
            model_name='todo_model',
            old_name='created_time',
            new_name='Created_time',
        ),
        migrations.RenameField(
            model_name='todo_model',
            old_name='details',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='todo_model',
            old_name='important',
            new_name='Important',
        ),
        migrations.RenameField(
            model_name='todo_model',
            old_name='title',
            new_name='Title',
        ),
    ]
